packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@parcel/watcher': false
  core-js-pure: false
  esbuild: false
  sharp: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@types/node@26.1.0'
